{
    "th10_ascii_stage_1": "1 word: ",
    "th10_ascii_stage_2": "Step 2 ",
    "th10_ascii_stage_3": "Step 3 ",
    "th10_ascii_stage_4": "Phase 4: ",
    "th10_ascii_stage_5": "section 5 ",
    "th10_ascii_stage_6": "Levele 6",
    "th10_ascii_stage_clear": "Gold  ",
    "th10_ascii_score_empty": "%2d  %s  %9ld%d  ----/--/-- --:--  steps -  ---%",
    "th10_ascii_ranking": "            Of course !!",
    "th06_ascii_reimu_a": "reims",
    "th06_ascii_reimu_b": "Eh",
    "th06_ascii_marisa_a": "MARY",
    "th06_ascii_marisa_b": "Marysab",
    "th10 Music Room spoiler 1": "<c$** The selected instrument has not yet been played **$>",
    "th10 Music Room spoiler 2": "<c$Destructive songs can be added to the list.$>",
    "th10 Music Room spoiler 3": "<c$Do you still want to play this song?$>",
    "th10 Music Room spoiler 4": "<c$If you want to play, click on the button again.$>",
    "th10 Music Room spoiler 5": "<c$If you don't want to play, shake the spring.$>",
    "th10 Dialog Prompt": "Select Windows mode.",
    "th10 Dialog Fullscreen": "LEARNING ACTIVITIES",
    "th10 Dialog Always ask": "Ask the owner",
    "th10 config": "Touhou fuujinroku is a special community event",
    "th10 faith meter": "Increase confidence in the player.",
    "th10 screen mode": "Face",
    "th10 always ask": "comes back every now and then",
    "th10 slowshot": "Consider the result",
    "th06 fullscreen": "LEARNING ACTIVITIES",
    "th06 windowed": "Create a window",
    "th06 colors": "Colorful design",
    "th07 32bits mode": "Page 32 (emotional)",
    "th06 16bits mode": "16 pieces",
    "th06 refresh rate": "leave the law",
    "th06 half rate": "1/2 /. |",
    "th06 third rate": "2 seconds",
    "th06 config saved caption": "Agreed",
    "th06 config saved text": "Save the archive.",
    "th07 DirectInput": "Do not use direct tactics to control your thoughts.",
    "th09 full rate": "Yes (basic)",
    "th09 no save": "Set up anonymous pages",
    "th09 save": "Records and recovery.",
    "th10 JP": "New Eastern Six",
    "th10": "Strong East Wind: Rock of Faith",
}